repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v5.0.0
   hooks:
    - id: check-json
    - id: check-yaml
    - id: check-xml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: debug-statements
    - id: check-docstring-first
 - repo: https://github.com/astral-sh/ruff-pre-commit
   rev: v0.8.4
   hooks:
     - id: ruff
       args: [ --fix, --exit-non-zero-on-fix ]
